### ISSUE TITLE
Nothing works?

### ISSUE THREAD

**Issue by dubefab** [Floydv149/bibleLinkerPro#1]
I enabled the plugin and type in ge 1:1 and it detects nothing? I tried [Genesis 1:1], nothing.

**Comment by Floydv149** [comment]
I'm sorry to hear that it does not work for you.

This could be due to you not selecting the text ("ge 1:1").
You can also turn on a feature that automatically gets your currently selected line, so you don't have to select it manually.

For that, go to the plugin's settings and turn on the setting "Auto get current line".

I hope that works for you, and if not, I am happy to help you further.
