### ISSUE TITLE
Similar plugin: JW Library Verse Link

### ISSUE THREAD

**Issue by MrBertie** [Floydv149/bibleLinkerPro#2]
Interesting coincidence that I found your plugin the day after I finished my own version for my own use: [jwlib-verse-link](https://github.com/MrBertie/jwlib-verse-link); I took a different approach to you and only display the links in the (HTML) Reading View.

**Comment by Floydv149** [comment]
Very interesting 😄 
I took a look at your plugin. Really like your code. Very handy that you don't have the links in your source code, but only in your reading view. I took my other approach, so that you could execute a command to convert a text to a link, so that, while taking notes, you can automatically go to that text in JW Library, and don't have to switch to the reading view for that 😉
